### ISSUE TITLE
Unable to get Filter to work

### ISSUE THREAD

**Issue by zoiter8683** [nnance/homebridge-august-locks#13]
**Describe Your Problem:**
I'm trying to use the Filter and i'm unable to get the syntax correct, or the feature isn't working, but i'm thinking its my syntax. I've got 2 locks i need to ignore. These are locks where i'm a guest. I grabbed the IDs out of the Homebridge log and took just the ID values from each long and put a comma between them.

**Logs:**
```

[3/7/2022, 3:28:57 PM] [August Locks] [{"id":"1234567890ABC","name":"Guest Garage Door","macAddress":"LockMacAddress","houseId":"HouseIDValue","houseName":"Not My House"},{"id":"ABC123567890","name":"Guest Front Door","macAddress":"LockMacAddress","houseId":"HouseIDValue","houseName":"NotMyHouse"},{"id":"987654321CBA","name":"My Front Door","macAddress":"LockMacAddress","houseId":"houseIDValue","houseName":"My House"}]
[3/7/2022, 3:28:57 PM] [August Locks] Restoring existing accessory from cache: Guest Garage Door
[3/7/2022, 3:28:57 PM] [August Locks] Restoring existing accessory from cache: Guest Front Door
[3/7/2022, 3:28:57 PM] [August Locks] Restoring existing accessory from cache: My Front Door

[3/7/2022, 3:28:58 PM] [August Locks] {"code":"NotAuthorized","message":"user {MyUserID redacted} is not authorized to manage lock 1234567890ABC"}
[3/7/2022, 3:28:58 PM] [August Locks] Get Lock Status -> Error: Unknown lock status for lock 1234567890ABC
    at augustGetLockStatus (/homebridge/node_modules/homebridge-august-locks/src/august.ts:228:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[3/7/2022, 3:28:58 PM] [August Locks] {"code":"NotAuthorized","message":"user {MyUserID redacted} is not authorized to manage lock ABC123567890"}
[3/7/2022, 3:28:58 PM] [August Locks] Get Lock Status -> Error: Unknown lock status for lock ABC123567890
    at augustGetLockStatus (/homebridge/node_modules/homebridge-august-locks/src/august.ts:228:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Plugin Config:**

```json
        {
            "name": "August Locks",
            "email": "myEmailaddress",
            "password": "myPassword",
            "code": "my2FA code",
            "installId": "myGUID",
            "filter": "1234567890ABC,ABC123567890",
            "_bridge": {
                "username": "macvaluehere",
                "port": 52356
            },
            "platform": "AugustLocks"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.7.4
* **Homebridge Version**: 1.4.0
* **Node.js Version**: 16.14.0
* **NPM Version**: 8.3.1
* **Operating System**: Docker (Alpine Linux (3.12.9))

**Comment by fratinize** [comment]
similar issue. What is this Feild Looking for as Far as Format? Tried Lock ID with and Without Quotes, Also Tried House ID with and without Quotes. Same Result, Continues to Show Lock We Don't want. TY

**Comment by Hulkkih** [comment]
Same problem here. Im able to hide only one lock. Hope we get a fix soon.

**Comment by fratinize** [comment]
@Hulkkih how did you get even 1? to hide

**Comment by Hulkkih** [comment]
Just added lockID in plugin settings. Multiple lockID should be separated with comma but that doesnt' seem to work.

**Comment by wongchristopher** [comment]
I put up a pull request to fix this.  @nnance  just needs to merge it.

https://github.com/nnance/homebridge-august-locks/pull/12

**Comment by mojodean** [comment]
Not sure if @nnance is still around or maintaining this. Has not been in active development since January.

**Comment by Hulkkih** [comment]
> Not sure if @nnance is still around or maintaining this. Has not been in active development since January. 

Is there any way to get someone to continue his work? Atleast get this filter thing to work?

**Comment by wongchristopher** [comment]
If you take a look at my diff and manually put the changes in it will work.  Just a shame he hasn't merged my pull request in.  It's a quick one line change.
