### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by jthun** [nnance/homebridge-august-locks#18]
Hi,

I'm getting an error after adding the August plugin.

`[01/08/2022, 15:02:49] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/homebridge-august-locks@1.7.4/node_modules/homebridge-august-locks/src/august.ts:108:25)
    at IncomingMessage.emit (node:events:527:28)
    at IncomingMessage.Readable.read (node:internal/streams/readable:527:10)
    at flow (node:internal/streams/readable:1011:34)
    at resume_ (node:internal/streams/readable:992:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

With debug enabled, it looks like the response from the August API is chunked:

```
[01/08/2022, 15:02:49] [Yale Locks] statusCode: 200

[01/08/2022, 15:02:49] [Yale Locks] {"Email":"<redacted>","PhoneNo":"<redacted>","UserID":"<redacted>","FirstName":"<redacted>","LastName":"<redacted>","imageInfo":{"original":{"width":831,"height":831,"format":"webp","url":"https://<redacted>.webp","secure_url":"https://<redacted>.webp"},"thumbnail":{"width":128,"height":128,"format":"webp","url":"https://<redacted>.webp","secure_url":"https://<redacted>.webp"}},"locale":{"language":"sv","country":"SE"},"optedInToOrchestra":false,"tokens":[{"type":"subscriptio

[01/08/2022, 15:02:49] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/homebridge-august-locks@1.7.4/node_modules/homebridge-august-locks/src/august.ts:108:25)
    at IncomingMessage.emit (node:events:527:28)
    at IncomingMessage.Readable.read (node:internal/streams/readable:527:10)
    at flow (node:internal/streams/readable:1011:34)
    at resume_ (node:internal/streams/readable:992:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

[01/08/2022, 15:02:49] [Yale Locks] statusCode: 200

[01/08/2022, 15:02:49] [Yale Locks] n-management","token":"server-removed"}]}

[01/08/2022, 15:02:49] SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/homebridge-august-locks@1.7.4/node_modules/homebridge-august-locks/src/august.ts:108:25)
    at IncomingMessage.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at IncomingMessage.Readable.push (node:internal/streams/readable:228:10)
    at HTTPParser.parserOnBody (node:_http_common:141:24)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
```

My three locks are visible in the iOS UI, but it's not possible to change the status, and the status is not updated after manual lock/unlock.

Is there a limitation in response length perhaps, that might be exceeded when I've added a profile picture in the Yale Access app?

**Comment by KevinZhou92** [comment]
I think the json response is truncated.

If you turn on debug mode, you will see that the json response is truncated.

I also noticed that after multiple restarts, the august plugin starts successfully.

We need to fix the json process though. Check JSON fetching example from [here](https://nodejs.org/api/http.html)

**Comment by scottrobertson** [comment]
Also seeing this

**Comment by chris3g** [comment]
This started happening for me when I added a profile photo on my august account. It seems it makes the JSON response too long. Unfortunately I can’t find any way to remove a profile photo once set, you can only change it.

**Comment by KevinZhou92** [comment]
Hi Guys, here is a temporary fix for the issue. Replace the file in `/usr/lib/node_modules/homebridge-august-locks/dist/august.js` with the below snippet. Hope this helps.
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.augustSetStatus = exports.augustGetLockStatus = exports.augustGetLocks = exports.augustGetHouses = exports.augustStartSession = exports.AugustLockStatus = void 0;
const https_1 = require("https");
const util_1 = require("util");
var AugustLockStatus;
(function (AugustLockStatus) {
    AugustLockStatus[AugustLockStatus["LOCKED"] = 0] = "LOCKED";
    AugustLockStatus[AugustLockStatus["UNLOCKED"] = 1] = "UNLOCKED";
    AugustLockStatus[AugustLockStatus["UNKNOWN"] = 2] = "UNKNOWN";
})(AugustLockStatus = exports.AugustLockStatus || (exports.AugustLockStatus = {}));
async function augustStartSession(options, log) {
    const { uuid, code, idType, password, identifier } = options;
    const session = await augustLogin(uuid, idType, identifier, password, log);
    log.debug(JSON.stringify(session));
    const { status } = await augustGetMe(session, log);
    // Session isn't valid yet, so we need to validate it by sending a code
    if (status !== 200) {
        if (code === undefined || code.length === 0) {
            await augustSendCode(session, log);
            log.info('Session is not valid yet, but no code was provided. Please provide a code.');
        }
        else {
            const resp = await augustValidateCode(code, session, log);
            if (resp.status !== 200) {
                await augustSendCode(session, log);
                log.error(`Invalid code: ${resp.status}, new code sent, please provide the new code.`);
            }
            else {
                session.token = resp.token;
            }
        }
    }
    return session;
}
exports.augustStartSession = augustStartSession;
function getRequestOptions(path, method) {
    return {
        hostname: 'api-production.august.com',
        port: 443,
        path: path,
        method: method,
        headers: {
            'x-august-api-key': '7cab4bbd-2693-4fc1-b99b-dec0fb20f9d4',
            'x-kease-api-key': '7cab4bbd-2693-4fc1-b99b-dec0fb20f9d4',
            'Content-Type': 'application/json',
            'Accept-Version': '0.0.1',
            'User-Agent': 'August/Luna-3.2.2',
        },
    };
}
function addToken(options, token) {
    const newOptions = {
        ...options,
    };
    if (newOptions['headers']) {
        newOptions['headers']['x-august-access-token'] = token;
    }
    return newOptions;
}
async function makeRequest(options, data, log) {
    return new Promise((resolve, reject) => {
        const req = (0, https_1.request)(options, res => {
        	let returnValue = '';
            res.on('data', chunk => {
                log.debug(`statusCode: ${res.statusCode}`);
                returnValue += chunk;
                log.debug(chunk.toString('utf-8'));
            });
            res.on('end', () => {
                if (res.statusCode === 200) {
                    resolve({
                    status: res.statusCode,
                    token: res.headers['x-august-access-token'],
                    payload: JSON.parse(returnValue.toString()),
                	});
                } else {
                    reject(returnValue);
                }
            });
        });
        req.on('error', error => {
            log.error(`request error: ${error}`);
            reject(error);
        });
        req.write(data);
        req.end();
    });
}
async function augustLogin(uuid, idType, identifier, password, log) {
    const data = new util_1.TextEncoder().encode(JSON.stringify({
        identifier: `${idType}:${identifier}`,
        password: password,
        installId: uuid,
    }));
    const options = getRequestOptions('/session', 'POST');
    const res = await makeRequest(options, data, log);
    if (res.status !== 200 || res.payload['userId'] === undefined || res.payload['userId'].length === 0) {
        throw new Error(`Invalid user credentials: ${res.status}`);
    }
    else {
        return {
            idType: idType,
            identifier: identifier,
            token: res.token,
        };
    }
}
async function augustGetMe(session, log) {
    const options = addToken(getRequestOptions('/users/me', 'GET'), session.token);
    return makeRequest(options, new util_1.TextEncoder().encode(''), log);
}
async function augustSendCode(session, log) {
    const data = new util_1.TextEncoder().encode(JSON.stringify({
        value: session.identifier,
    }));
    const options = addToken(getRequestOptions(`/validation/${session.idType}`, 'POST'), session.token);
    return makeRequest(options, data, log);
}
async function augustValidateCode(code, session, log) {
    const payload = {
        code,
    };
    payload[session.idType] = session.identifier;
    const data = new util_1.TextEncoder().encode(JSON.stringify(payload));
    const options = addToken(getRequestOptions(`/validate/${session.idType}`, 'POST'), session.token);
    return makeRequest(options, data, log);
}
async function augustGetHouses(session, log) {
    const options = addToken(getRequestOptions('/users/houses/mine', 'GET'), session.token);
    const results = await makeRequest(options, new Uint8Array(), log);
    if (results.status === 200 && Array.isArray(results.payload)) {
        const homes = (results.payload).map(home => ({
            id: home['HouseID'],
            name: home['HouseName'],
        }));
        return homes;
    }
    else {
        return [];
    }
}
exports.augustGetHouses = augustGetHouses;
async function augustGetLocks(session, log) {
    const options = addToken(getRequestOptions('/users/locks/mine', 'GET'), session.token);
    const results = await makeRequest(options, new Uint8Array(), log);
    if (results.status === 200 && results.payload) {
        const locks = Object.keys(results.payload).map(id => {
            const lock = results.payload[id];
            return {
                id: id,
                name: lock['LockName'],
                macAddress: lock['macAddress'],
                houseId: lock['HouseID'],
                houseName: lock['HouseName'],
            };
        });
        return locks;
    }
    else {
        return [];
    }
}
exports.augustGetLocks = augustGetLocks;
async function augustGetLockStatus(session, lockId, log) {
    const options = addToken(getRequestOptions(`/remoteoperate/${lockId}/status`, 'PUT'), session.token);
    const results = await makeRequest(options, new Uint8Array(), log);
    const status = results.payload['status'];
    if (status === 'kAugLockState_Locked') {
        return AugustLockStatus.LOCKED;
    }
    else if (status === 'kAugLockState_Unlocked') {
        return AugustLockStatus.UNLOCKED;
    }
    else {
        log.info(JSON.stringify(results.payload));
        throw new Error(`Unknown lock status for lock ${lockId}`);
    }
}
exports.augustGetLockStatus = augustGetLockStatus;
async function augustSetStatus(session, lockId, status, log) {
    const url = status === AugustLockStatus.LOCKED ? `/remoteoperate/${lockId}/lock` : `/remoteoperate/${lockId}/unlock`;
    const options = addToken(getRequestOptions(url, 'PUT'), session.token);
    const results = await makeRequest(options, new Uint8Array(), log);
    const update = results.payload['status'] === 'kAugLockState_Locked' ? AugustLockStatus.LOCKED : AugustLockStatus.UNLOCKED;
    return update;
}
exports.augustSetStatus = augustSetStatus;
//# sourceMappingURL=august.js.map
```

**Comment by chris3g** [comment]
Thank you, it's working for me.

**Comment by scottrobertson** [comment]
I am getting the following with this change.

```
[15/10/2022, 10:31:56] [August Locks] Failed to start session, check your config and confirm your password
```

Details are 100% correct.

**Comment by scottrobertson** [comment]
```
[15/10/2022, 13:46:28] [August Locks] {"code":"InvalidCredentials","message":"unverified access token"}
```

**Comment by KevinZhou92** [comment]
@scottrobertson Hi Scott, would you mind resetting your august plugin? I didn't change any logic about sending the request, i just updated the logic for receiving the response.

**Comment by scottrobertson** [comment]
Thanks @KevinZhou92. Not sure what happened there. Totally uninstalled and reinstalled and now it's all good.

**Comment by Taraan03** [comment]
I had this same issue and the fix from @KevinZhou92 got me working again. Thanks!
