### ISSUE TITLE
Code 97 Bridge in use error

### ISSUE THREAD

**Issue by jlg89** [nnance/homebridge-august-locks#20]
**Describe The Bug:**
Code: 97 Bridge in use error, causing continuous restart of bridge

**To Reproduce:**
Fresh plug-in install & config

**Expected behavior:**
No errors

**Logs:**

```
9/25/2022, 2:13:14 PMDoor Access Bridge starting
9/25/2022, 2:13:17 PMDoor Access BridgeLoaded plugin 'homebridge-august-locks'
9/25/2022, 2:13:17 PMDoor Access BridgeLoading 1 platforms...
9/25/2022, 2:13:17 PMDoor Access BridgeEBC August LocksLoading accessory from cache: Nursery Exit
9/25/2022, 2:13:17 PMDoor Access BridgeEBC August LocksLoading accessory from cache: Welcome Area
9/25/2022, 2:13:17 PMDoor Access BridgeEBC August LocksLoading accessory from cache: Office Entrance
9/25/2022, 2:13:17 PMDoor Access BridgeEBC August LocksLoading accessory from cache: Kitchen Exit
9/25/2022, 2:13:17 PMDoor Access BridgeEBC August LocksLoading accessory from cache: Fellowship Double Door
9/25/2022, 2:13:17 PMDoor Access BridgeEBC August LocksLoading accessory from cache: Education Back Exit
9/25/2022, 2:13:17 PMDoor Access BridgeBridge is running on port 51846.
9/25/2022, 2:13:18 PMDoor Access BridgeEBC August Locks[{"id":"2C7C3EEFF31949FEA480F681BC2B26FD","name":"Nursery Exit","macAddress":"78:9C:85:06:D5:9D","houseId":"168311cb-6607-4cc2-8b18-74597039c9af","houseName":"Emmanuel Baptist Church"},{"id":"391A60EFF6EB4B84BEF8DF8518207A9F","name":"Welcome Area","macAddress":"78:9C:85:11:30:FB","houseId":"168311cb-6607-4cc2-8b18-74597039c9af","houseName":"Emmanuel Baptist Church"},{"id":"48DCBCF475324439A24FC2E671C09F26","name":"Office Entrance","macAddress":"78:9C:85:04:60:19","houseId":"168311cb-6607-4cc2-8b18-74597039c9af","houseName":"Emmanuel Baptist Church"},{"id":"52C1E8497D1143EBBD17DE00041CE52D","name":"Kitchen Exit","macAddress":"78:9C:85:06:B6:13","houseId":"168311cb-6607-4cc2-8b18-74597039c9af","houseName":"Emmanuel Baptist Church"},{"id":"75B3F786AEDA4926A43F11C4E2F1D17B","name":"Fellowship Double Door","macAddress":"78:9C:85:06:D4:C3","houseId":"168311cb-6607-4cc2-8b18-74597039c9af","houseName":"Emmanuel Baptist Church"},{"id":"FF2891DDFDA146208BD8DC977BD25660","name":"Education Back Exit","macAddress":"78:9C:85:03:A9:99","houseId":"168311cb-6607-4cc2-8b18-74597039c9af","houseName":"Emmanuel Baptist Church"}]
9/25/2022, 2:13:18 PMDoor Access BridgeEBC August LocksRestoring existing accessory from cache: Nursery Exit
9/25/2022, 2:13:18 PMDoor Access BridgeEBC August LocksRestoring existing accessory from cache: Welcome Area
9/25/2022, 2:13:18 PMDoor Access BridgeEBC August LocksRestoring existing accessory from cache: Office Entrance
9/25/2022, 2:13:18 PMDoor Access BridgeEBC August LocksRestoring existing accessory from cache: Kitchen Exit
9/25/2022, 2:13:18 PMDoor Access BridgeEBC August LocksRestoring existing accessory from cache: Fellowship Double Door
9/25/2022, 2:13:18 PMDoor Access BridgeEBC August LocksRestoring existing accessory from cache: Education Back Exit
9/25/2022, 2:13:22 PMDoor Access BridgeEBC August Locks{"code":97,"message":"Bridge in use"}
9/25/2022, 2:13:22 PMDoor Access BridgeEBC August LocksERRORGet Lock Status -> Error: Unknown lock status for lock 75B3F786AEDA4926A43F11C4E2F1D17B at augustGetLockStatus (/var/lib/hoobs/dooraccessbridge/node_modules/homebridge-august-locks/src/august.ts:228:11) at processTicksAndRejections (node:internal/process/task_queues:96:5)
9/25/2022, 2:13:23 PMDoor Access BridgeEBC August Locks{"code":97,"message":"Bridge in use"}
9/25/2022, 2:13:23 PMDoor Access BridgeEBC August LocksERRORGet Lock Status -> Error: Unknown lock status for lock 391A60EFF6EB4B84BEF8DF8518207A9F at augustGetLockStatus (/var/lib/hoobs/dooraccessbridge/node_modules/homebridge-august-locks/src/august.ts:228:11) at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Plugin Config:**

```json
{
"platform": "AugustLocks",
"name": "EBC August Locks",
"email": "<account email>",
"password": "<account password>",
"installId": "<generated uid>",
"code": "<received code>"
}
```

**Environment:**

* **Plugin Version**: 1.7.4
* **Homebridge Version**: 1.5.0
* **Node.js Version**: 16.17.1
* **NPM Version**: 8.15.0
* **Operating System**: Linux hoobs 5.10.103-v71+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv71 GNU/Linux

**Comment by jlg89** [comment]
Seeing the Code 97 error every 10s. Also seeing Code 102 LockCommandTimeout error every 30s. 

At some point I get "request error: Error: Parse Error: JS Exception" and the bridge/plugin restarts.

**Comment by SkyroOryks** [comment]
Been having this issue as well

**Comment by marksmith1701** [comment]
Any update on this...seeing this as well.

**Comment by jlg89** [comment]
Try the homebridge-august plugin, it seems to be more robust.
