### ISSUE TITLE
State out of sync when communication error occurs

### ISSUE THREAD

**Issue by nnance** [nnance/homebridge-august-locks#5]
**Describe The Bug:**
Get HomeKit notifications about locks being unlocked when they haven't been changed.

**To Reproduce:**
Just happens occasionally

**Expected behavior:**
Should only change state when the lock physically changes state

**Logs:**
[12/27/2021, 8:41:22 PM] [August Locks] request error: Error: socket hang up
[12/27/2021, 8:41:22 PM] [August Locks] Get Lock Status -> Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}

**Comment by gwilliams1205** [comment]
I am running into this issue currently.. getting notifications in the middle of the night. I see you have some updates.. Should we see a fix coming soon? 

Thank you!
